name: jsonstudio
base: core24
version: '0.1'
summary: JSON editor and viewer (Qt)
description: |
  jsonStudio is a simple JSON editor/viewer built with Qt and Python.
  It supports viewing as a tree, validation, filtering and basic styling.

grade: stable
confinement: strict

# Target platforms for core24
platforms:
  amd64:
    # Build the amd64 snap on either amd64 or arm64 builders
    build-on: [amd64, arm64]
  arm64:
    # Build the arm64 snap on an arm64 builder
    build-on: [arm64]

apps:
  jsonstudio:
    command: bin/jsonstudio
    plugs:
      - x11
      - wayland
      - opengl
      - network
      - home
      - audio-playback
    environment:
      QT_QPA_PLATFORM: xcb

parts:
  jsonstudio:
    plugin: nil
    source: ..
    stage-packages:
      - python3
      - python3-pyqt5
      - python3-jsonschema
      - libgl1
      - libglib2.0-0
      - libx11-6
      - libxkbcommon0
      - libxext6
      - libxrender1
      - libxi6
      - libxfixes3
      - libxrandr2
      - libxinerama1
      - libxcb1
      - libxcb-keysyms1
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-icccm4
    override-build: |
      set -eux
      # Install launcher
      install -D -m 0755 /dev/stdin "$CRAFT_PART_INSTALL/bin/jsonstudio" <<'EOF'
      #!/bin/sh
      export QT_QPA_PLATFORM=${QT_QPA_PLATFORM:-xcb}
      cd "$SNAP/TODO/tools/jsonStudio"
      exec /usr/bin/python3 main.py "$@"
      EOF

      # Copy application sources into the snap
      mkdir -p "$CRAFT_PART_INSTALL/TODO/tools/jsonStudio"
      cp -a "$CRAFT_PART_SRC"/. "$CRAFT_PART_INSTALL/TODO/tools/jsonStudio/"

      # Ensure desktop entry and icons are available during prime/pack
      if [ -d "$CRAFT_PART_SRC/snap/gui" ]; then
        mkdir -p "$CRAFT_PART_INSTALL/snap/gui" "$CRAFT_PART_INSTALL/meta/gui"
        cp -a "$CRAFT_PART_SRC/snap/gui/." "$CRAFT_PART_INSTALL/snap/gui/"
        cp -a "$CRAFT_PART_SRC/snap/gui/." "$CRAFT_PART_INSTALL/meta/gui/"
      fi
