name: jsonstudio
base: core24
adopt-info: meta                      # <- versão vem deste "part"
summary: JSON editor and viewer (Qt)
description: |
  jsonStudio is a simple JSON editor/viewer built with Qt and Python.
  It supports viewing as a tree, validation, filtering and basic styling.

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64, arm64]
  arm64:
    build-on: [arm64]

apps:
  jsonstudio:
    command: bin/jsonstudio
    plugs:
      - x11
      - wayland
      - opengl
      - network
      - home
      - audio-playback
    environment:
      QT_QPA_PLATFORM: xcb

parts:
  meta:
    plugin: nil
    source: ..
    build-packages:
      - git
    override-pull: |
      set -eux

      # Só tenta usar git se houver repositório
      if [ -d ".git" ] && command -v git >/dev/null 2>&1; then
        git fetch --tags || true
        ver="$(git describe --tags --always 2>/dev/null || true)"
      else
        ver=""
      fi

      # Fallback limpo (sem sufixo "-g" vazio)
      if [ -z "${ver:-}" ]; then
        ver="$(date -u +%Y.%m.%d)"
        # tenta adicionar hash curto se existir git e repo
        if command -v git >/dev/null 2>&1 && [ -d ".git" ]; then
          sha="$(git rev-parse --short HEAD 2>/dev/null || true)"
          [ -n "$sha" ] && ver="${ver}-g${sha}"
        fi
      fi

      craftctl set version="$ver"

  # --- A aplicação em si (PyQt) ---
  jsonstudio:
    plugin: python
    source: ..
    build-packages:
      - rsync
    stage-packages:
      - python3
      - python3-pyqt5
      - python3-jsonschema
      - libgl1
      - libglib2.0-0
      - libx11-6
      - libxkbcommon0
      - libxext6
      - libxrender1
      - libxi6
      - libxfixes3
      - libxrandr2
      - libxinerama1
      - libxcb1
      - libxcb-keysyms1
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-icccm4

    override-build: |
      set -eux
      craftctl default

      # Launcher
      install -D -m 0755 /dev/stdin "$CRAFT_PART_INSTALL/bin/jsonstudio" <<'EOF'
      #!/bin/sh
      export QT_QPA_PLATFORM="${QT_QPA_PLATFORM:-xcb}"
      PYBIN="$SNAP/venv/bin/python3"; [ -x "$PYBIN" ] || PYBIN="/usr/bin/python3"
      cd "$SNAP/app"
      exec "$PYBIN" main.py "$@"
      EOF

      # Copiar apenas o código da app (excluindo lixo de build/CI)
      mkdir -p "$CRAFT_PART_INSTALL/app"
      rsync -a --delete \
        --exclude="/.git" \
        --exclude="/.github" \
        --exclude="/.cache" \
        --exclude="/parts" \
        --exclude="/prime" \
        --exclude="/stage" \
        --exclude="/*.snap" \
        --exclude="/snap" \
        "$CRAFT_PART_SRC"/ \
        "$CRAFT_PART_INSTALL/app/"

      # .desktop e ícones (mantém)
      if [ -d "$CRAFT_PART_SRC/snap/gui" ]; then
        mkdir -p "$CRAFT_PART_INSTALL/snap/gui" "$CRAFT_PART_INSTALL/meta/gui"
        cp -a "$CRAFT_PART_SRC/snap/gui/." "$CRAFT_PART_INSTALL/snap/gui/"
        cp -a "$CRAFT_PART_SRC/snap/gui/." "$CRAFT_PART_INSTALL/meta/gui/"
      fi
