name: Build & Publish Snap

on:
  push:
    branches: [ "main" ]          # muda se usares outra branch
    paths:
      - "snap/**"
      - "**/*.py"
      - ".github/workflows/snap.yml"
  workflow_dispatch: {}            # permite correr manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: snapcore/action-build@v1
        id: build

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
